// Generate part code preview
// Format: {TYPE}-{SEQUENCE}
// Example: MAG-0001 or PRT-0001
// Note: Actual part code is generated by backend with proper sequence numbering

export const generatePartCode = (
  rollerType: string
): string => {
  // Get type prefix - matches backend logic
  const typePrefix = rollerType === 'Magnetic Roller' ? 'MAG' : 'PRT'

  // Generate random sequence for preview (actual sequence from database)
  const sequence = Math.floor(Math.random() * 9999) + 1
  const sequenceStr = sequence.toString().padStart(4, '0')

  return `${typePrefix}-${sequenceStr}`
}
