import {
  ChildPartProductionOrder,
  ChildPartStatus,
  ProcessType,
  ProcessStatus,
  ChildPartProcess
} from "@/types/child-part-production";

// Helper function to create process sequences
const createShaftProcessSequence = (): ChildPartProcess[] => [
  {
    processId: "proc-mat-001",
    processName: "Material Issue",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 1,
    estimatedCycleTimeMin: 0,
    estimatedSetupTimeMin: 5,
    actualStartTime: new Date("2025-01-15T10:00:00"),
    actualEndTime: new Date("2025-01-15T10:05:00"),
    status: ProcessStatus.Completed,
    operatorName: "Store Keeper",
    remarks: "EN19 Rod Ø75x500 issued"
  },
  {
    processId: "proc-cnc-001",
    processName: "CNC Turning 1st",
    processType: ProcessType.CNC,
    machineId: "CNC-01",
    sequence: 2,
    estimatedCycleTimeMin: 45,
    estimatedSetupTimeMin: 15,
    actualStartTime: new Date("2025-01-15T10:30:00"),
    actualEndTime: new Date("2025-01-15T14:30:00"),
    status: ProcessStatus.Completed,
    operatorName: "Ramesh",
    remarks: "Roughing completed"
  },
  {
    processId: "proc-cnc-002",
    processName: "CNC Turning 2nd",
    processType: ProcessType.CNC,
    machineId: "CNC-01",
    sequence: 3,
    estimatedCycleTimeMin: 50,
    estimatedSetupTimeMin: 10,
    actualStartTime: new Date("2025-01-16T09:00:00"),
    actualEndTime: null,
    status: ProcessStatus.InProgress,
    operatorName: "Ramesh",
    remarks: "Semi-finishing in progress"
  },
  {
    processId: "proc-cnc-003",
    processName: "CNC Turning 3rd",
    processType: ProcessType.CNC,
    machineId: "CNC-02",
    sequence: 4,
    estimatedCycleTimeMin: 40,
    estimatedSetupTimeMin: 10,
    actualStartTime: null,
    actualEndTime: null,
    status: ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  },
  {
    processId: "proc-grn-001",
    processName: "Grinding OD",
    processType: ProcessType.GRINDING,
    machineId: "GRN-01",
    sequence: 5,
    estimatedCycleTimeMin: 30,
    estimatedSetupTimeMin: 15,
    actualStartTime: null,
    actualEndTime: null,
    status: ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  },
  {
    processId: "proc-grn-002",
    processName: "Grinding Finish",
    processType: ProcessType.GRINDING,
    machineId: "GRN-02",
    sequence: 6,
    estimatedCycleTimeMin: 25,
    estimatedSetupTimeMin: 10,
    actualStartTime: null,
    actualEndTime: null,
    status: ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  },
  {
    processId: "proc-qc-001",
    processName: "Quality Check",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 7,
    estimatedCycleTimeMin: 10,
    estimatedSetupTimeMin: 0,
    actualStartTime: null,
    actualEndTime: null,
    status: ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  },
  {
    processId: "proc-rfa-001",
    processName: "Ready for Assembly",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 8,
    estimatedCycleTimeMin: 0,
    estimatedSetupTimeMin: 0,
    actualStartTime: null,
    actualEndTime: null,
    status: ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  }
];

const createPipeProcessSequence = (isCompleted: boolean): ChildPartProcess[] => [
  {
    processId: "proc-mat-003",
    processName: "Material Issue",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 1,
    estimatedCycleTimeMin: 0,
    estimatedSetupTimeMin: 5,
    actualStartTime: isCompleted ? new Date("2025-01-14T09:00:00") : null,
    actualEndTime: isCompleted ? new Date("2025-01-14T09:05:00") : null,
    status: isCompleted ? ProcessStatus.Completed : ProcessStatus.Pending,
    operatorName: isCompleted ? "Store Keeper" : null,
    remarks: isCompleted ? "SS Pipe issued" : null
  },
  {
    processId: "proc-cnc-004",
    processName: "CNC Turning 1st",
    processType: ProcessType.CNC,
    machineId: "CNC-03",
    sequence: 2,
    estimatedCycleTimeMin: 35,
    estimatedSetupTimeMin: 12,
    actualStartTime: isCompleted ? new Date("2025-01-14T10:00:00") : null,
    actualEndTime: isCompleted ? new Date("2025-01-14T13:00:00") : null,
    status: isCompleted ? ProcessStatus.Completed : ProcessStatus.Pending,
    operatorName: isCompleted ? "Suresh" : null,
    remarks: null
  },
  {
    processId: "proc-grn-003",
    processName: "Grinding OD",
    processType: ProcessType.GRINDING,
    machineId: "GRN-01",
    sequence: 3,
    estimatedCycleTimeMin: 28,
    estimatedSetupTimeMin: 10,
    actualStartTime: isCompleted ? new Date("2025-01-14T14:00:00") : null,
    actualEndTime: isCompleted ? new Date("2025-01-14T16:30:00") : null,
    status: isCompleted ? ProcessStatus.Completed : ProcessStatus.Pending,
    operatorName: isCompleted ? "Prakash" : null,
    remarks: null
  },
  {
    processId: "proc-qc-002",
    processName: "Quality Check",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 4,
    estimatedCycleTimeMin: 8,
    estimatedSetupTimeMin: 0,
    actualStartTime: isCompleted ? new Date("2025-01-14T16:45:00") : null,
    actualEndTime: isCompleted ? new Date("2025-01-14T16:53:00") : null,
    status: isCompleted ? ProcessStatus.Completed : ProcessStatus.Pending,
    operatorName: isCompleted ? "Inspector" : null,
    remarks: null
  },
  {
    processId: "proc-rfa-002",
    processName: "Ready for Assembly",
    processType: ProcessType.MANUAL,
    machineId: null,
    sequence: 5,
    estimatedCycleTimeMin: 0,
    estimatedSetupTimeMin: 0,
    actualStartTime: isCompleted ? new Date("2025-01-14T17:00:00") : null,
    actualEndTime: isCompleted ? new Date("2025-01-14T17:00:00") : null,
    status: isCompleted ? ProcessStatus.Completed : ProcessStatus.Pending,
    operatorName: null,
    remarks: null
  }
];

// Mock child part production orders for ORD-001 (Magnetic Roller)
export const mockChildPartProduction: ChildPartProductionOrder[] = [
  {
    id: "cpp-001",
    childPartId: "bom-item-001",
    childPartName: "Shaft",
    parentOrderId: "ord-001",
    parentOrderNo: "ORD-001",
    rawMaterialId: "rm-001",
    rawMaterialGrade: "EN19",
    rawMaterialQtyRequired: 2.5,
    rawMaterialUnit: "kg",
    quantityRequired: 2,
    quantityProduced: 1,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.InProcess,
    processSequence: createShaftProcessSequence(),
    currentProcessId: "proc-cnc-002",
    currentProcessName: "CNC Turning 2nd",
    currentMachineId: "CNC-01",
    plannedStartDate: new Date("2025-01-15T09:00:00"),
    actualStartDate: new Date("2025-01-15T10:00:00"),
    plannedCompletionDate: new Date("2025-01-17T17:00:00"),
    actualCompletionDate: null,
    readyForAssemblyDate: null,
    assignedOperator: "Ramesh",
    jobCardNumber: "JC-001-SHAFT",
    isAssemblyReady: false,
    blockingReason: null,
    productName: "Magnetic Roller 300x1000",
    icon: "🔧",
    progressPercentage: 60
  },
  {
    id: "cpp-002",
    childPartId: "bom-item-002",
    childPartName: "Tikki",
    parentOrderId: "ord-001",
    parentOrderNo: "ORD-001",
    rawMaterialId: "rm-002",
    rawMaterialGrade: "EN8",
    rawMaterialQtyRequired: 1.8,
    rawMaterialUnit: "kg",
    quantityRequired: 5,
    quantityProduced: 2,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.InProcess,
    processSequence: [
      {
        processId: "proc-mat-004",
        processName: "Material Issue",
        processType: ProcessType.MANUAL,
        machineId: null,
        sequence: 1,
        estimatedCycleTimeMin: 0,
        estimatedSetupTimeMin: 5,
        actualStartTime: new Date("2025-01-15T11:00:00"),
        actualEndTime: new Date("2025-01-15T11:05:00"),
        status: ProcessStatus.Completed,
        operatorName: "Store Keeper",
        remarks: null
      },
      {
        processId: "proc-cnc-005",
        processName: "CNC Turning 1st",
        processType: ProcessType.CNC,
        machineId: "CNC-02",
        sequence: 2,
        estimatedCycleTimeMin: 38,
        estimatedSetupTimeMin: 12,
        actualStartTime: new Date("2025-01-15T14:00:00"),
        actualEndTime: new Date("2025-01-16T10:00:00"),
        status: ProcessStatus.Completed,
        operatorName: "Prakash",
        remarks: null
      },
      {
        processId: "proc-cnc-006",
        processName: "CNC Turning 2nd",
        processType: ProcessType.CNC,
        machineId: "CNC-02",
        sequence: 3,
        estimatedCycleTimeMin: 42,
        estimatedSetupTimeMin: 10,
        actualStartTime: new Date("2025-01-16T11:00:00"),
        actualEndTime: null,
        status: ProcessStatus.InProgress,
        operatorName: "Prakash",
        remarks: null
      },
      {
        processId: "proc-grn-004",
        processName: "Grinding",
        processType: ProcessType.GRINDING,
        machineId: "GRN-02",
        sequence: 4,
        estimatedCycleTimeMin: 25,
        estimatedSetupTimeMin: 10,
        actualStartTime: null,
        actualEndTime: null,
        status: ProcessStatus.Pending,
        operatorName: null,
        remarks: null
      }
    ],
    currentProcessId: "proc-cnc-006",
    currentProcessName: "CNC Turning 2nd",
    currentMachineId: "CNC-02",
    plannedStartDate: new Date("2025-01-15T11:00:00"),
    actualStartDate: new Date("2025-01-15T11:00:00"),
    plannedCompletionDate: new Date("2025-01-18T16:00:00"),
    actualCompletionDate: null,
    readyForAssemblyDate: null,
    assignedOperator: "Prakash",
    jobCardNumber: "JC-001-TIKKI",
    isAssemblyReady: false,
    blockingReason: "In process - CNC Turning 2nd",
    productName: "Magnetic Roller 300x1000",
    icon: "🔩",
    progressPercentage: 40
  },
  {
    id: "cpp-003",
    childPartId: "bom-item-003",
    childPartName: "Pipe",
    parentOrderId: "ord-001",
    parentOrderNo: "ORD-001",
    rawMaterialId: "rm-003",
    rawMaterialGrade: "SS304",
    rawMaterialQtyRequired: 8.5,
    rawMaterialUnit: "kg",
    quantityRequired: 5,
    quantityProduced: 5,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.ReadyForAssembly,
    processSequence: createPipeProcessSequence(true),
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-14T09:00:00"),
    actualStartDate: new Date("2025-01-14T09:00:00"),
    plannedCompletionDate: new Date("2025-01-14T17:00:00"),
    actualCompletionDate: new Date("2025-01-14T17:00:00"),
    readyForAssemblyDate: new Date("2025-01-15T09:00:00"),
    assignedOperator: null,
    jobCardNumber: "JC-001-PIPE",
    isAssemblyReady: true,
    blockingReason: null,
    productName: "Magnetic Roller 300x1000",
    icon: "📏",
    progressPercentage: 100
  },
  {
    id: "cpp-004",
    childPartId: "bom-item-004",
    childPartName: "Gear",
    parentOrderId: "ord-001",
    parentOrderNo: "ORD-001",
    rawMaterialId: "rm-004",
    rawMaterialGrade: "EN19",
    rawMaterialQtyRequired: 1.2,
    rawMaterialUnit: "kg",
    quantityRequired: 5,
    quantityProduced: 0,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.NotStarted,
    processSequence: [
      {
        processId: "proc-mat-005",
        processName: "Material Issue",
        processType: ProcessType.MANUAL,
        machineId: null,
        sequence: 1,
        estimatedCycleTimeMin: 0,
        estimatedSetupTimeMin: 5,
        actualStartTime: null,
        actualEndTime: null,
        status: ProcessStatus.Pending,
        operatorName: null,
        remarks: null
      },
      {
        processId: "proc-cnc-007",
        processName: "CNC Turning",
        processType: ProcessType.CNC,
        machineId: "CNC-03",
        sequence: 2,
        estimatedCycleTimeMin: 40,
        estimatedSetupTimeMin: 15,
        actualStartTime: null,
        actualEndTime: null,
        status: ProcessStatus.Pending,
        operatorName: null,
        remarks: null
      },
      {
        processId: "proc-hob-001",
        processName: "Hobbing",
        processType: ProcessType.HOBBING,
        machineId: "HOB-01",
        sequence: 3,
        estimatedCycleTimeMin: 55,
        estimatedSetupTimeMin: 20,
        actualStartTime: null,
        actualEndTime: null,
        status: ProcessStatus.Pending,
        operatorName: null,
        remarks: null
      }
    ],
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-17T09:00:00"),
    actualStartDate: null,
    plannedCompletionDate: new Date("2025-01-20T17:00:00"),
    actualCompletionDate: null,
    readyForAssemblyDate: null,
    assignedOperator: null,
    jobCardNumber: "JC-001-GEAR",
    isAssemblyReady: false,
    blockingReason: "Material EN19 not issued",
    productName: "Magnetic Roller 300x1000",
    icon: "⚙️",
    progressPercentage: 0
  },
  {
    id: "cpp-005",
    childPartId: "bom-item-005",
    childPartName: "Bearings",
    parentOrderId: "ord-001",
    parentOrderNo: "ORD-001",
    rawMaterialId: "comp-001",
    rawMaterialGrade: "6204-2RS",
    rawMaterialQtyRequired: 20,
    rawMaterialUnit: "pcs",
    quantityRequired: 20,
    quantityProduced: 20,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.ReadyForAssembly,
    processSequence: [
      {
        processId: "proc-pur-001",
        processName: "Purchased Component",
        processType: ProcessType.MANUAL,
        machineId: null,
        sequence: 1,
        estimatedCycleTimeMin: 0,
        estimatedSetupTimeMin: 0,
        actualStartTime: new Date("2025-01-14T10:00:00"),
        actualEndTime: new Date("2025-01-14T10:00:00"),
        status: ProcessStatus.Completed,
        operatorName: "Purchase Dept",
        remarks: "Purchased from vendor"
      }
    ],
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-14T10:00:00"),
    actualStartDate: new Date("2025-01-14T10:00:00"),
    plannedCompletionDate: new Date("2025-01-14T10:00:00"),
    actualCompletionDate: new Date("2025-01-14T10:00:00"),
    readyForAssemblyDate: new Date("2025-01-14T10:00:00"),
    assignedOperator: null,
    jobCardNumber: "JC-001-BEAR",
    isAssemblyReady: true,
    blockingReason: null,
    productName: "Magnetic Roller 300x1000",
    icon: "🔘",
    progressPercentage: 100
  }
];

// Mock child part production for ORD-002 (Rubber Roller) - All ready
export const mockChildPartProductionOrd002: ChildPartProductionOrder[] = [
  {
    id: "cpp-006",
    childPartId: "bom-item-006",
    childPartName: "Shaft",
    parentOrderId: "ord-002",
    parentOrderNo: "ORD-002",
    rawMaterialId: "rm-001",
    rawMaterialGrade: "EN19",
    rawMaterialQtyRequired: 2.0,
    rawMaterialUnit: "kg",
    quantityRequired: 2,
    quantityProduced: 2,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.ReadyForAssembly,
    processSequence: createShaftProcessSequence().map(p => ({ ...p, status: ProcessStatus.Completed })),
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-10T09:00:00"),
    actualStartDate: new Date("2025-01-10T09:00:00"),
    plannedCompletionDate: new Date("2025-01-12T17:00:00"),
    actualCompletionDate: new Date("2025-01-12T16:00:00"),
    readyForAssemblyDate: new Date("2025-01-13T09:00:00"),
    assignedOperator: null,
    jobCardNumber: "JC-002-SHAFT",
    isAssemblyReady: true,
    blockingReason: null,
    productName: "Rubber Roller 250x800",
    icon: "🔧",
    progressPercentage: 100
  },
  {
    id: "cpp-007",
    childPartId: "bom-item-007",
    childPartName: "Pipe",
    parentOrderId: "ord-002",
    parentOrderNo: "ORD-002",
    rawMaterialId: "rm-005",
    rawMaterialGrade: "MS Pipe",
    rawMaterialQtyRequired: 6.5,
    rawMaterialUnit: "kg",
    quantityRequired: 3,
    quantityProduced: 3,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.ReadyForAssembly,
    processSequence: createPipeProcessSequence(true),
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-11T09:00:00"),
    actualStartDate: new Date("2025-01-11T09:00:00"),
    plannedCompletionDate: new Date("2025-01-12T17:00:00"),
    actualCompletionDate: new Date("2025-01-12T15:00:00"),
    readyForAssemblyDate: new Date("2025-01-13T09:00:00"),
    assignedOperator: null,
    jobCardNumber: "JC-002-PIPE",
    isAssemblyReady: true,
    blockingReason: null,
    productName: "Rubber Roller 250x800",
    icon: "📏",
    progressPercentage: 100
  },
  {
    id: "cpp-008",
    childPartId: "bom-item-008",
    childPartName: "Bearings",
    parentOrderId: "ord-002",
    parentOrderNo: "ORD-002",
    rawMaterialId: "comp-002",
    rawMaterialGrade: "6203-2RS",
    rawMaterialQtyRequired: 12,
    rawMaterialUnit: "pcs",
    quantityRequired: 12,
    quantityProduced: 12,
    quantityRejected: 0,
    quantityInRework: 0,
    status: ChildPartStatus.ReadyForAssembly,
    processSequence: [
      {
        processId: "proc-pur-002",
        processName: "Purchased Component",
        processType: ProcessType.MANUAL,
        machineId: null,
        sequence: 1,
        estimatedCycleTimeMin: 0,
        estimatedSetupTimeMin: 0,
        actualStartTime: new Date("2025-01-10T10:00:00"),
        actualEndTime: new Date("2025-01-10T10:00:00"),
        status: ProcessStatus.Completed,
        operatorName: "Purchase Dept",
        remarks: "Purchased from vendor"
      }
    ],
    currentProcessId: null,
    currentProcessName: null,
    currentMachineId: null,
    plannedStartDate: new Date("2025-01-10T10:00:00"),
    actualStartDate: new Date("2025-01-10T10:00:00"),
    plannedCompletionDate: new Date("2025-01-10T10:00:00"),
    actualCompletionDate: new Date("2025-01-10T10:00:00"),
    readyForAssemblyDate: new Date("2025-01-10T10:00:00"),
    assignedOperator: null,
    jobCardNumber: "JC-002-BEAR",
    isAssemblyReady: true,
    blockingReason: null,
    productName: "Rubber Roller 250x800",
    icon: "🔘",
    progressPercentage: 100
  }
];

export const allChildPartProduction = [
  ...mockChildPartProduction,
  ...mockChildPartProductionOrd002
];
