import { Component, ComponentCategory } from '@/types'

export const mockComponents: Component[] = [
  {
    id: 'comp-1',
    partNumber: 'BRG-6205-2RS',
    componentName: 'Deep Groove Ball Bearing 6205-2RS',
    category: ComponentCategory.BEARING,
    manufacturer: 'SKF',
    supplierName: 'Industrial Bearings Ltd',
    specifications: 'ID: 25mm, OD: 52mm, Width: 15mm, Sealed both sides',
    unitCost: 450,
    leadTimeDays: 7,
    unit: 'pcs',
    notes: 'Used in standard magnetic rollers',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-28')
  },
  {
    id: 'comp-2',
    partNumber: 'BRG-6206-ZZ',
    componentName: 'Deep Groove Ball Bearing 6206-ZZ',
    category: ComponentCategory.BEARING,
    manufacturer: 'NTN',
    supplierName: 'Industrial Bearings Ltd',
    specifications: 'ID: 30mm, OD: 62mm, Width: 16mm, Shielded both sides',
    unitCost: 520,
    leadTimeDays: 7,
    unit: 'pcs',
    notes: 'Used in heavy-duty rollers',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-27')
  },
  {
    id: 'comp-3',
    partNumber: 'GR-M2-Z40',
    componentName: 'Spur Gear Module 2, 40 Teeth',
    category: ComponentCategory.GEAR,
    manufacturer: 'Precision Gears Co',
    supplierName: 'Motion Components India',
    specifications: 'Module: 2, Teeth: 40, Bore: 20mm, Material: EN8',
    unitCost: 850,
    leadTimeDays: 10,
    unit: 'pcs',
    notes: 'Standard drive gear for roller synchronization',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-26')
  },
  {
    id: 'comp-4',
    partNumber: 'GR-M2.5-Z32',
    componentName: 'Helical Gear Module 2.5, 32 Teeth',
    category: ComponentCategory.GEAR,
    manufacturer: 'Precision Gears Co',
    supplierName: 'Motion Components India',
    specifications: 'Module: 2.5, Teeth: 32, Bore: 25mm, Helix Angle: 20°',
    unitCost: 1250,
    leadTimeDays: 14,
    unit: 'pcs',
    notes: 'Used in high-speed printing rollers',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-25')
  },
  {
    id: 'comp-5',
    partNumber: 'SEAL-OIL-35X52X7',
    componentName: 'Oil Seal 35x52x7',
    category: ComponentCategory.SEAL,
    manufacturer: 'NOK Corporation',
    supplierName: 'Seal & Gasket Supplies',
    specifications: 'Inner Dia: 35mm, Outer Dia: 52mm, Width: 7mm, NBR Material',
    unitCost: 120,
    leadTimeDays: 5,
    unit: 'pcs',
    notes: 'Standard shaft seal for bearings',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-28')
  },
  {
    id: 'comp-6',
    partNumber: 'SEAL-OIL-40X62X8',
    componentName: 'Oil Seal 40x62x8',
    category: ComponentCategory.SEAL,
    manufacturer: 'NOK Corporation',
    supplierName: 'Seal & Gasket Supplies',
    specifications: 'Inner Dia: 40mm, Outer Dia: 62mm, Width: 8mm, Viton Material',
    unitCost: 185,
    leadTimeDays: 5,
    unit: 'pcs',
    notes: 'High-temperature seal for special applications',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-27')
  },
  {
    id: 'comp-7',
    partNumber: 'CPL-FLEX-D30',
    componentName: 'Flexible Coupling D30',
    category: ComponentCategory.COUPLING,
    manufacturer: 'Lovejoy India',
    supplierName: 'Power Transmission Co',
    specifications: 'Bore: 20-30mm, Torque: 50 Nm, Misalignment: 1°',
    unitCost: 950,
    leadTimeDays: 12,
    unit: 'pcs',
    notes: 'For motor-roller connection',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-24')
  },
  {
    id: 'comp-8',
    partNumber: 'SHAFT-D25-L150',
    componentName: 'Precision Shaft D25 x L150',
    category: ComponentCategory.SHAFT,
    manufacturer: 'In-house',
    specifications: 'Diameter: 25mm, Length: 150mm, Material: EN8, Hardened',
    unitCost: 380,
    leadTimeDays: 3,
    unit: 'pcs',
    notes: 'Pre-machined shaft blanks',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-28')
  },
  {
    id: 'comp-9',
    partNumber: 'BUSH-BR-25X30',
    componentName: 'Bronze Bushing 25x30',
    category: ComponentCategory.BUSHING,
    manufacturer: 'Kirloskar Ferrous',
    supplierName: 'Metal Components Ltd',
    specifications: 'ID: 25mm, OD: 30mm, Length: 30mm, Bronze alloy',
    unitCost: 220,
    leadTimeDays: 8,
    unit: 'pcs',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-26')
  },
  {
    id: 'comp-10',
    partNumber: 'BOLT-M8X40',
    componentName: 'Hex Bolt M8x40 Grade 8.8',
    category: ComponentCategory.FASTENER,
    manufacturer: 'Sundram Fasteners',
    supplierName: 'Hardware Suppliers Inc',
    specifications: 'Thread: M8, Length: 40mm, Grade: 8.8, Zinc plated',
    unitCost: 8,
    leadTimeDays: 2,
    unit: 'pcs',
    notes: 'Standard assembly bolts',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-28')
  },
  {
    id: 'comp-11',
    partNumber: 'NUT-M8-SS',
    componentName: 'Hex Nut M8 Stainless Steel',
    category: ComponentCategory.FASTENER,
    manufacturer: 'Sundram Fasteners',
    supplierName: 'Hardware Suppliers Inc',
    specifications: 'Thread: M8, Material: SS304, Finish: Polished',
    unitCost: 5,
    leadTimeDays: 2,
    unit: 'pcs',
    notes: 'Corrosion-resistant nuts for critical assemblies',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-28')
  },
  {
    id: 'comp-12',
    partNumber: 'KEY-8X7X50',
    componentName: 'Parallel Key 8x7x50',
    category: ComponentCategory.OTHER,
    manufacturer: 'Precision Keys Mfg',
    supplierName: 'Industrial Components Co',
    specifications: 'Width: 8mm, Height: 7mm, Length: 50mm, EN8 Material',
    unitCost: 25,
    leadTimeDays: 4,
    unit: 'pcs',
    notes: 'For shaft-gear/pulley connection',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-27')
  }
]
