// Centralized mock data exports
export * from './customers'
export * from './products'
export * from './product-templates'
export * from './orders'
export * from './raw-materials'
export * from './components'
export * from './processes'
export * from './boms'
export * from './job-cards'
