import { Machine, MachineQueueItem } from "@/types/machine";
import { MachineType } from "@/types/pfd-template";
import { Priority } from "@/types/enums";

export const mockMachines: Machine[] = [
  {
    id: "cnc-01",
    machineCode: "CNC-01",
    machineName: "CNC Lathe 1",
    machineType: MachineType.CNC_LATHE,
    isOperational: true,
    shiftHoursPerDay: 16,
    utilizationTarget: 85,
    currentJobCardId: "JC-001-SHAFT",
    currentJobCardNo: "JC-001-SHAFT",
    currentOrderNo: "ORD-001",
    currentProcessName: "CNC Turning 2nd",
    currentOperatorId: "op-001",
    currentOperatorName: "Ramesh",
    estimatedBusyUntil: new Date("2025-01-16T11:20:00"),
    currentProgress: 60,
    currentElapsedMin: 30,
    currentTotalMin: 50,
    queuedJobCards: [
      {
        jobCardId: "JC-003-PIPE",
        orderNo: "ORD-003",
        processName: "CNC Turning 1st",
        estimatedSetupMin: 12,
        estimatedCycleMin: 45,
        estimatedStartTime: new Date("2025-01-16T11:30:00"),
        estimatedEndTime: new Date("2025-01-16T12:27:00"),
        priority: Priority.HIGH
      },
      {
        jobCardId: "JC-005-SHAFT",
        orderNo: "ORD-005",
        processName: "CNC Turning 3rd",
        estimatedSetupMin: 10,
        estimatedCycleMin: 40,
        estimatedStartTime: new Date("2025-01-16T12:30:00"),
        estimatedEndTime: new Date("2025-01-16T13:20:00"),
        priority: Priority.MEDIUM
      }
    ],
    totalQueueTimeMin: 107,
    currentUtilizationPercent: 85
  },
  {
    id: "cnc-02",
    machineCode: "CNC-02",
    machineName: "CNC Lathe 2",
    machineType: MachineType.CNC_LATHE,
    isOperational: true,
    shiftHoursPerDay: 16,
    utilizationTarget: 85,
    currentJobCardId: "JC-001-TIKKI",
    currentJobCardNo: "JC-001-TIKKI",
    currentOrderNo: "ORD-001",
    currentProcessName: "CNC Turning 2nd",
    currentOperatorId: "op-002",
    currentOperatorName: "Prakash",
    estimatedBusyUntil: new Date("2025-01-16T12:00:00"),
    currentProgress: 45,
    currentElapsedMin: 19,
    currentTotalMin: 42,
    queuedJobCards: [
      {
        jobCardId: "JC-001-SHAFT",
        orderNo: "ORD-001",
        processName: "CNC Turning 3rd",
        estimatedSetupMin: 10,
        estimatedCycleMin: 40,
        estimatedStartTime: new Date("2025-01-16T12:10:00"),
        estimatedEndTime: new Date("2025-01-16T13:00:00"),
        priority: Priority.HIGH
      }
    ],
    totalQueueTimeMin: 50,
    currentUtilizationPercent: 65
  },
  {
    id: "cnc-03",
    machineCode: "CNC-03",
    machineName: "CNC Lathe 3",
    machineType: MachineType.CNC_LATHE,
    isOperational: true,
    shiftHoursPerDay: 8,
    utilizationTarget: 85,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [],
    totalQueueTimeMin: 0,
    currentUtilizationPercent: 20
  },
  {
    id: "vmc-01",
    machineCode: "VMC-01",
    machineName: "VMC Machine 1",
    machineType: MachineType.VMC,
    isOperational: true,
    shiftHoursPerDay: 8,
    utilizationTarget: 80,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [],
    totalQueueTimeMin: 0,
    currentUtilizationPercent: 15
  },
  {
    id: "grn-01",
    machineCode: "GRN-01",
    machineName: "Grinding Machine 1",
    machineType: MachineType.GRINDING_MACHINE,
    isOperational: true,
    shiftHoursPerDay: 16,
    utilizationTarget: 85,
    currentJobCardId: "JC-002-PIPE",
    currentJobCardNo: "JC-002-PIPE",
    currentOrderNo: "ORD-002",
    currentProcessName: "Grinding OD",
    currentOperatorId: "op-003",
    currentOperatorName: "Suresh",
    estimatedBusyUntil: new Date("2025-01-16T10:50:00"),
    currentProgress: 80,
    currentElapsedMin: 24,
    currentTotalMin: 30,
    queuedJobCards: [
      {
        jobCardId: "JC-004-SHAFT",
        orderNo: "ORD-004",
        processName: "Grinding OD",
        estimatedSetupMin: 15,
        estimatedCycleMin: 30,
        estimatedStartTime: new Date("2025-01-16T11:00:00"),
        estimatedEndTime: new Date("2025-01-16T11:45:00"),
        priority: Priority.HIGH
      },
      {
        jobCardId: "JC-006-PIPE",
        orderNo: "ORD-006",
        processName: "Grinding OD",
        estimatedSetupMin: 12,
        estimatedCycleMin: 28,
        estimatedStartTime: new Date("2025-01-16T11:50:00"),
        estimatedEndTime: new Date("2025-01-16T12:30:00"),
        priority: Priority.MEDIUM
      },
      {
        jobCardId: "JC-007-SHAFT",
        orderNo: "ORD-007",
        processName: "Grinding Finish",
        estimatedSetupMin: 10,
        estimatedCycleMin: 25,
        estimatedStartTime: new Date("2025-01-16T12:35:00"),
        estimatedEndTime: new Date("2025-01-16T13:10:00"),
        priority: Priority.LOW
      }
    ],
    totalQueueTimeMin: 120,
    currentUtilizationPercent: 90
  },
  {
    id: "grn-02",
    machineCode: "GRN-02",
    machineName: "Grinding Machine 2",
    machineType: MachineType.GRINDING_MACHINE,
    isOperational: true,
    shiftHoursPerDay: 16,
    utilizationTarget: 85,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [
      {
        jobCardId: "JC-001-TIKKI",
        orderNo: "ORD-001",
        processName: "Grinding",
        estimatedSetupMin: 10,
        estimatedCycleMin: 25,
        estimatedStartTime: new Date("2025-01-16T14:00:00"),
        estimatedEndTime: new Date("2025-01-16T14:35:00"),
        priority: Priority.HIGH
      }
    ],
    totalQueueTimeMin: 35,
    currentUtilizationPercent: 45
  },
  {
    id: "grn-03",
    machineCode: "GRN-03",
    machineName: "Grinding Machine 3",
    machineType: MachineType.GRINDING_MACHINE,
    isOperational: true,
    shiftHoursPerDay: 8,
    utilizationTarget: 85,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [],
    totalQueueTimeMin: 0,
    currentUtilizationPercent: 30
  },
  {
    id: "grn-04",
    machineCode: "GRN-04",
    machineName: "Grinding Machine 4 (Finish)",
    machineType: MachineType.GRINDING_MACHINE,
    isOperational: true,
    shiftHoursPerDay: 8,
    utilizationTarget: 85,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [],
    totalQueueTimeMin: 0,
    currentUtilizationPercent: 25
  },
  {
    id: "hob-01",
    machineCode: "HOB-01",
    machineName: "Hobbing Machine 1",
    machineType: MachineType.HOBBING_MACHINE,
    isOperational: true,
    shiftHoursPerDay: 8,
    utilizationTarget: 75,
    currentJobCardId: null,
    currentJobCardNo: null,
    currentOrderNo: null,
    currentProcessName: null,
    currentOperatorId: null,
    currentOperatorName: null,
    estimatedBusyUntil: null,
    currentProgress: 0,
    currentElapsedMin: 0,
    currentTotalMin: 0,
    queuedJobCards: [],
    totalQueueTimeMin: 0,
    currentUtilizationPercent: 40
  }
];

// Calculate overall shop floor utilization
export const calculateOverallUtilization = (): number => {
  const totalUtilization = mockMachines.reduce(
    (sum, machine) => sum + machine.currentUtilizationPercent,
    0
  );
  return Math.round(totalUtilization / mockMachines.length);
};
