import { OSPTransaction, OSPStatus, OSPProcessType } from "@/types/osp-tracking";

export const mockOSPTransactions: OSPTransaction[] = [
  {
    id: "osp-001",
    orderId: "ord-001",
    orderNo: "ORD-001",
    childPartId: "cpp-001",
    childPartName: "Shaft",
    processId: "proc-ht-001",
    processName: "Heat Treatment",
    vendorId: "vendor-001",
    vendorName: "ABC Heat Treatment Pvt Ltd",
    ospProcessType: OSPProcessType.HEAT_TREATMENT,
    quantitySent: 5,
    quantityReceived: 0,
    quantityRejected: 0,
    sentDate: new Date("2025-01-10T09:00:00"),
    expectedReturnDate: new Date("2025-01-15T17:00:00"),
    actualReturnDate: null,
    status: OSPStatus.IN_PROCESS,
    delayDays: 2,
    challanNumber: "CH-12345",
    invoiceNumber: null,
    invoiceAmount: null,
    receivedWithIssues: false,
    issueDescription: null,
  },
  {
    id: "osp-002",
    orderId: "ord-003",
    orderNo: "ORD-003",
    childPartId: "cpp-009",
    childPartName: "Pipe",
    processId: "proc-black-001",
    processName: "Blackening",
    vendorId: "vendor-002",
    vendorName: "XYZ Surface Coating",
    ospProcessType: OSPProcessType.BLACKENING,
    quantitySent: 10,
    quantityReceived: 0,
    quantityRejected: 0,
    sentDate: new Date("2025-01-14T10:00:00"),
    expectedReturnDate: new Date("2025-01-18T17:00:00"),
    actualReturnDate: null,
    status: OSPStatus.READY,
    delayDays: 0,
    challanNumber: "CH-12346",
    invoiceNumber: "INV-2025-001",
    invoiceAmount: 2500,
    receivedWithIssues: false,
    issueDescription: null,
  },
  {
    id: "osp-003",
    orderId: "ord-005",
    orderNo: "ORD-005",
    childPartId: "cpp-010",
    childPartName: "Tikki",
    processId: "proc-anod-001",
    processName: "Anodising",
    vendorId: "vendor-003",
    vendorName: "PQR Anodising Works",
    ospProcessType: OSPProcessType.ANODISING,
    quantitySent: 15,
    quantityReceived: 0,
    quantityRejected: 0,
    sentDate: new Date("2025-01-16T11:00:00"),
    expectedReturnDate: new Date("2025-01-20T17:00:00"),
    actualReturnDate: null,
    status: OSPStatus.IN_PROCESS,
    delayDays: null,
    challanNumber: "CH-12347",
    invoiceNumber: null,
    invoiceAmount: null,
    receivedWithIssues: false,
    issueDescription: null,
  },
  {
    id: "osp-004",
    orderId: "ord-002",
    orderNo: "ORD-002",
    childPartId: "cpp-007",
    childPartName: "Pipe",
    processId: "proc-chrome-001",
    processName: "Chrome Plating",
    vendorId: "vendor-004",
    vendorName: "LMN Plating Services",
    ospProcessType: OSPProcessType.CHROME_PLATING,
    quantitySent: 3,
    quantityReceived: 3,
    quantityRejected: 0,
    sentDate: new Date("2025-01-08T09:00:00"),
    expectedReturnDate: new Date("2025-01-12T17:00:00"),
    actualReturnDate: new Date("2025-01-12T15:00:00"),
    status: OSPStatus.RECEIVED,
    delayDays: null,
    challanNumber: "CH-12344",
    invoiceNumber: "INV-2025-002",
    invoiceAmount: 4500,
    receivedWithIssues: false,
    issueDescription: null,
  },
  {
    id: "osp-005",
    orderId: "ord-004",
    orderNo: "ORD-004",
    childPartId: "cpp-011",
    childPartName: "Gear",
    processId: "proc-ht-002",
    processName: "Heat Treatment",
    vendorId: "vendor-001",
    vendorName: "ABC Heat Treatment Pvt Ltd",
    ospProcessType: OSPProcessType.HEAT_TREATMENT,
    quantitySent: 8,
    quantityReceived: 6,
    quantityRejected: 2,
    sentDate: new Date("2025-01-09T10:00:00"),
    expectedReturnDate: new Date("2025-01-14T17:00:00"),
    actualReturnDate: new Date("2025-01-15T10:00:00"),
    status: OSPStatus.RECEIVED,
    delayDays: 1,
    challanNumber: "CH-12348",
    invoiceNumber: "INV-2025-003",
    invoiceAmount: 6000,
    receivedWithIssues: true,
    issueDescription: "2 pieces rejected due to hardness out of specification",
  },
];
