import {
  PFDTemplate,
  ProcessCategory,
  ProcessSubCategory,
  MachineType,
  MagneticProcessType,
  CNCOperationType
} from "@/types/pfd-template";
import { RollerType } from "@/types/enums";

// Printing Roller - Shaft PFD
export const printingRollerShaftPFD: PFDTemplate = {
  id: "pfd-printing-shaft-001",
  productType: RollerType.PRINTING,
  childPartType: "Shaft",
  version: "1.0",
  isActive: true,
  processFlow: [
    {
      stepNumber: 1,
      processId: "proc-mat-001",
      processName: "Material Issue",
      processCategory: ProcessCategory.MANUAL_OPERATION,
      subCategory: null,
      icon: "📦",
      color: "#6b7280",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 5,
      cycleTimeMin: 0,
      isParallelizable: false,
      dependsOnSteps: [],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Issue EN19 Rod as per drawing specification",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    },
    {
      stepNumber: 2,
      processId: "proc-cnc-001",
      processName: "CNC Turning 1st (Roughing)",
      processCategory: ProcessCategory.CNC_TURNING,
      subCategory: ProcessSubCategory.TURNING_1ST,
      icon: "🔧",
      color: "#3b82f6",
      machineType: MachineType.CNC_LATHE,
      defaultMachineId: "CNC-01",
      allowedMachines: ["CNC-01", "CNC-02"],
      setupTimeMin: 15,
      cycleTimeMin: 45,
      isParallelizable: false,
      dependsOnSteps: [1],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isCNC: true,
      cncSequence: 1,
      cncOperationType: CNCOperationType.ROUGHING
    },
    {
      stepNumber: 3,
      processId: "proc-cnc-002",
      processName: "CNC Turning 2nd (Semi-Finish)",
      processCategory: ProcessCategory.CNC_TURNING,
      subCategory: ProcessSubCategory.TURNING_2ND,
      icon: "🔧",
      color: "#3b82f6",
      machineType: MachineType.CNC_LATHE,
      defaultMachineId: "CNC-01",
      allowedMachines: ["CNC-01", "CNC-02"],
      setupTimeMin: 10,
      cycleTimeMin: 50,
      isParallelizable: false,
      dependsOnSteps: [2],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isCNC: true,
      cncSequence: 2,
      cncOperationType: CNCOperationType.SEMI_FINISHING
    },
    {
      stepNumber: 4,
      processId: "proc-cnc-003",
      processName: "CNC Turning 3rd (Finishing)",
      processCategory: ProcessCategory.CNC_TURNING,
      subCategory: ProcessSubCategory.TURNING_3RD,
      icon: "🔧",
      color: "#3b82f6",
      machineType: MachineType.CNC_LATHE,
      defaultMachineId: "CNC-02",
      allowedMachines: ["CNC-02", "CNC-03"],
      setupTimeMin: 10,
      cycleTimeMin: 40,
      isParallelizable: false,
      dependsOnSteps: [3],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isCNC: true,
      cncSequence: 3,
      cncOperationType: CNCOperationType.FINISHING
    },
    {
      stepNumber: 5,
      processId: "proc-grn-001",
      processName: "Grinding OD",
      processCategory: ProcessCategory.GRINDING,
      subCategory: ProcessSubCategory.GRINDING_OD,
      icon: "💎",
      color: "#8b5cf6",
      machineType: MachineType.GRINDING_MACHINE,
      defaultMachineId: "GRN-01",
      allowedMachines: ["GRN-01", "GRN-02"],
      setupTimeMin: 15,
      cycleTimeMin: 30,
      isParallelizable: false,
      dependsOnSteps: [4],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    },
    {
      stepNumber: 6,
      processId: "proc-grn-002",
      processName: "Grinding Finish",
      processCategory: ProcessCategory.GRINDING,
      subCategory: ProcessSubCategory.GRINDING_FINISH,
      icon: "💎",
      color: "#8b5cf6",
      machineType: MachineType.GRINDING_MACHINE,
      defaultMachineId: "GRN-02",
      allowedMachines: ["GRN-02", "GRN-03"],
      setupTimeMin: 10,
      cycleTimeMin: 25,
      isParallelizable: false,
      dependsOnSteps: [5],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: true,
      inspectionCriteria: "Check surface finish Ra < 0.8",
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    },
    {
      stepNumber: 7,
      processId: "proc-qc-001",
      processName: "Quality Check",
      processCategory: ProcessCategory.INSPECTION,
      subCategory: null,
      icon: "✓",
      color: "#10b981",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 0,
      cycleTimeMin: 10,
      isParallelizable: false,
      dependsOnSteps: [6],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: true,
      inspectionCriteria: "Dimensional check, surface finish verification",
      isManual: true,
      manualInstructions: "Measure all critical dimensions as per drawing",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    },
    {
      stepNumber: 8,
      processId: "proc-rfa-001",
      processName: "Ready for Assembly",
      processCategory: ProcessCategory.ASSEMBLY,
      subCategory: null,
      icon: "✅",
      color: "#10b981",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 0,
      cycleTimeMin: 0,
      isParallelizable: false,
      dependsOnSteps: [7],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Move to assembly area",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    }
  ]
};

// Magnetic Roller - Main Body PFD
export const magneticRollerMainPFD: PFDTemplate = {
  id: "pfd-magnetic-001",
  productType: RollerType.MAGNETIC,
  childPartType: null,
  version: "1.0",
  isActive: true,
  processFlow: [
    {
      stepNumber: 1,
      processId: "proc-mat-002",
      processName: "Material Issue - Pipe",
      processCategory: ProcessCategory.MANUAL_OPERATION,
      subCategory: null,
      icon: "📦",
      color: "#6b7280",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 10,
      cycleTimeMin: 0,
      isParallelizable: false,
      dependsOnSteps: [],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Issue SS pipe as per specification",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    },
    {
      stepNumber: 2,
      processId: "proc-cnc-004",
      processName: "CNC Turning 1st - Pipe Ends",
      processCategory: ProcessCategory.CNC_TURNING,
      subCategory: ProcessSubCategory.TURNING_1ST,
      icon: "🔧",
      color: "#3b82f6",
      machineType: MachineType.CNC_LATHE,
      defaultMachineId: "CNC-03",
      allowedMachines: ["CNC-03", "CNC-04"],
      setupTimeMin: 15,
      cycleTimeMin: 60,
      isParallelizable: false,
      dependsOnSteps: [1],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isCNC: true,
      cncSequence: 1,
      cncOperationType: CNCOperationType.ROUGHING
    },
    {
      stepNumber: 3,
      processId: "proc-vmc-001",
      processName: "VMC Slotting for Magnets",
      processCategory: ProcessCategory.VMC,
      subCategory: ProcessSubCategory.VMC_SLOTTING,
      icon: "⚙️",
      color: "#8b5cf6",
      machineType: MachineType.VMC,
      defaultMachineId: "VMC-01",
      allowedMachines: ["VMC-01"],
      setupTimeMin: 20,
      cycleTimeMin: 90,
      isParallelizable: false,
      dependsOnSteps: [2],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: true,
      inspectionCriteria: "Check slot depth and width",
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.VMC_SLOTTING
    },
    {
      stepNumber: 4,
      processId: "proc-mag-001",
      processName: "Magnet Assembly",
      processCategory: ProcessCategory.MANUAL_OPERATION,
      subCategory: ProcessSubCategory.MANUAL_ASSEMBLY,
      icon: "🧲",
      color: "#ec4899",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 10,
      cycleTimeMin: 120,
      isParallelizable: false,
      dependsOnSteps: [3],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Insert magnets with correct polarity (N-S-N-S pattern)",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.MAGNET_ASSEMBLY,
      magnetQuantityFormula: "slotCount * 5"
    },
    {
      stepNumber: 5,
      processId: "proc-chem-001",
      processName: "Chemical Application",
      processCategory: ProcessCategory.MANUAL_OPERATION,
      subCategory: null,
      icon: "🧪",
      color: "#10b981",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 5,
      cycleTimeMin: 30,
      isParallelizable: false,
      dependsOnSteps: [4],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Apply epoxy resin coating evenly",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.CHEMICAL_APPLICATION,
      chemicalType: "Epoxy Resin ER-4000"
    },
    {
      stepNumber: 6,
      processId: "proc-vac-001",
      processName: "Vacuuming",
      processCategory: ProcessCategory.MANUAL_OPERATION,
      subCategory: null,
      icon: "🌀",
      color: "#06b6d4",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 5,
      cycleTimeMin: 20,
      isParallelizable: false,
      dependsOnSteps: [5],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Apply vacuum to remove air bubbles",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.VACUUMING,
      vacuumPressure: -80000
    },
    {
      stepNumber: 7,
      processId: "proc-heat-001",
      processName: "Heating Cycle",
      processCategory: ProcessCategory.HEAT_TREATMENT,
      subCategory: null,
      icon: "🔥",
      color: "#ef4444",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: "OVEN-01",
      allowedMachines: ["OVEN-01"],
      setupTimeMin: 10,
      cycleTimeMin: 180,
      isParallelizable: false,
      dependsOnSteps: [6],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: true,
      manualInstructions: "Heat at 180°C for 3 hours",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.HEATING_CYCLE,
      heatingTemperature: 180,
      heatingDurationMin: 180
    },
    {
      stepNumber: 8,
      processId: "proc-grn-003",
      processName: "Grinding 1st Pass",
      processCategory: ProcessCategory.GRINDING,
      subCategory: ProcessSubCategory.GRINDING_OD,
      icon: "💎",
      color: "#3b82f6",
      machineType: MachineType.GRINDING_MACHINE,
      defaultMachineId: "GRN-03",
      allowedMachines: ["GRN-03"],
      setupTimeMin: 15,
      cycleTimeMin: 45,
      isParallelizable: false,
      dependsOnSteps: [7],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.MULTI_STAGE_GRINDING
    },
    {
      stepNumber: 9,
      processId: "proc-grn-004",
      processName: "Grinding 2nd Pass",
      processCategory: ProcessCategory.GRINDING,
      subCategory: ProcessSubCategory.GRINDING_FINISH,
      icon: "💎",
      color: "#3b82f6",
      machineType: MachineType.GRINDING_MACHINE,
      defaultMachineId: "GRN-03",
      allowedMachines: ["GRN-03"],
      setupTimeMin: 10,
      cycleTimeMin: 40,
      isParallelizable: false,
      dependsOnSteps: [8],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: false,
      inspectionCriteria: null,
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.MULTI_STAGE_GRINDING
    },
    {
      stepNumber: 10,
      processId: "proc-grn-005",
      processName: "Grinding Finish",
      processCategory: ProcessCategory.GRINDING,
      subCategory: ProcessSubCategory.GRINDING_FINISH,
      icon: "💎",
      color: "#3b82f6",
      machineType: MachineType.GRINDING_MACHINE,
      defaultMachineId: "GRN-04",
      allowedMachines: ["GRN-04"],
      setupTimeMin: 10,
      cycleTimeMin: 35,
      isParallelizable: false,
      dependsOnSteps: [9],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: true,
      inspectionCriteria: "Final surface finish check",
      isManual: false,
      manualInstructions: null,
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null,
      isMagneticRollerProcess: true,
      magneticProcessType: MagneticProcessType.MULTI_STAGE_GRINDING
    },
    {
      stepNumber: 11,
      processId: "proc-qc-002",
      processName: "Final Inspection",
      processCategory: ProcessCategory.INSPECTION,
      subCategory: null,
      icon: "✓",
      color: "#10b981",
      machineType: MachineType.MANUAL_TOOL,
      defaultMachineId: null,
      allowedMachines: [],
      setupTimeMin: 0,
      cycleTimeMin: 15,
      isParallelizable: false,
      dependsOnSteps: [10],
      isOptional: false,
      optionalCondition: null,
      hasInspectionCheckpoint: true,
      inspectionCriteria: "Complete dimensional and functional check",
      isManual: true,
      manualInstructions: "Verify all specifications and magnet strength",
      isOutsourced: false,
      ospVendor: null,
      ospLeadTimeDays: null
    }
  ]
};

export const pfdTemplates: PFDTemplate[] = [
  printingRollerShaftPFD,
  magneticRollerMainPFD
];
