import { Product, RollerType } from '@/types'

// Products - Only Magnetic and Printing Rollers
export const mockProducts: Product[] = [
  // ===== MAGNETIC ROLLERS =====
  {
    id: 'prod-1',
    partCode: 'MAG-250-EN8-001',
    customerName: 'ABC Flexo Packaging Ltd.',
    modelName: 'Flexo 8-Color Press',
    rollerType: RollerType.MAGNETIC,
    diameter: 250,
    length: 1200,
    materialGrade: 'EN8',
    drawingNo: 'DRG-MAG-250-v2',
    revisionNo: 'R2',
    numberOfTeeth: null,
    surfaceFinish: 'Mirror Polish',
    hardness: 'HRC 58-62',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-20'),
    createdBy: 'admin'
  },
  {
    id: 'prod-2',
    partCode: 'MAG-280-EN8-002',
    customerName: 'Global Print Tech India',
    modelName: 'Rotogravure Press',
    rollerType: RollerType.MAGNETIC,
    diameter: 280,
    length: 1400,
    materialGrade: 'EN8',
    drawingNo: 'DRG-MAG-280-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Mirror Polish',
    hardness: 'HRC 58-62',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-10-15'),
    createdBy: 'admin'
  },
  {
    id: 'prod-3',
    partCode: 'MAG-300-EN19-003',
    customerName: 'Premium Packaging Solutions',
    modelName: 'CI Flexo Press',
    rollerType: RollerType.MAGNETIC,
    diameter: 300,
    length: 1600,
    materialGrade: 'EN19',
    drawingNo: 'DRG-MAG-300-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Mirror Polish',
    hardness: 'HRC 60-65',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-12-01'),
    createdBy: 'admin'
  },

  // ===== PRINTING ROLLERS =====
  {
    id: 'prod-4',
    partCode: 'PRT-200-NBR-001',
    customerName: 'XYZ Printing Solutions Pvt. Ltd.',
    modelName: 'Offset Press 4-Color',
    rollerType: RollerType.PRINTING,
    diameter: 200,
    length: 1000,
    materialGrade: 'NBR (Nitrile Rubber)',
    drawingNo: 'DRG-PRT-200-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Matt Finish',
    hardness: 'Shore A 70',
    processTemplateId: 'template-2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-11-10'),
    createdBy: 'admin'
  },
  {
    id: 'prod-5',
    partCode: 'PRT-250-PU-002',
    customerName: 'Industrial Print Corp',
    modelName: 'Web Offset Press',
    rollerType: RollerType.PRINTING,
    diameter: 250,
    length: 1200,
    materialGrade: 'Polyurethane',
    drawingNo: 'DRG-PRT-250-v2',
    revisionNo: 'R2',
    numberOfTeeth: null,
    surfaceFinish: 'Satin Finish',
    hardness: 'Shore A 80',
    processTemplateId: 'template-2',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-09-25'),
    createdBy: 'admin'
  },
  {
    id: 'prod-6',
    partCode: 'PRT-300-NBR-003',
    customerName: 'Pacific Printing Industries',
    modelName: 'Rotogravure Coating Line',
    rollerType: RollerType.PRINTING,
    diameter: 300,
    length: 1500,
    materialGrade: 'NBR (Nitrile Rubber)',
    drawingNo: 'DRG-PRT-300-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'High Gloss',
    hardness: 'Shore A 75',
    processTemplateId: 'template-2',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-30'),
    createdBy: 'admin'
  }
]
