import { Product, RollerType } from '@/types'

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    partCode: 'MAG-250-EN8-001',
    customerName: 'ABC Flexo Packaging Ltd.',
    modelName: 'Flexo 8-Color Press',
    rollerType: RollerType.MAGNETIC,
    diameter: 250,
    length: 1200,
    materialGrade: 'EN8',
    drawingNo: 'DRG-MAG-250-v2',
    revisionNo: 'R2',
    numberOfTeeth: null,
    surfaceFinish: 'Mirror Polish',
    hardness: 'HRC 58-62',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    createdBy: 'admin'
  },
  {
    id: 'prod-2',
    partCode: 'RUB-300-NBR-002',
    customerName: 'XYZ Printing Solutions Pvt. Ltd.',
    modelName: 'Offset Press 4-Color',
    rollerType: RollerType.RUBBER,
    diameter: 300,
    length: 1500,
    materialGrade: 'NBR (Nitrile Rubber)',
    drawingNo: 'DRG-RUB-300-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Matt Finish',
    hardness: 'Shore A 70',
    processTemplateId: 'template-2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    createdBy: 'admin'
  },
  {
    id: 'prod-3',
    partCode: 'ANI-200-EN19-003',
    customerName: 'PQR Industries Limited',
    modelName: 'Flexo CI Press',
    rollerType: RollerType.ANILOX,
    diameter: 200,
    length: 1000,
    materialGrade: 'EN19',
    drawingNo: 'DRG-ANI-200-v3',
    revisionNo: 'R3',
    numberOfTeeth: null,
    surfaceFinish: 'Ceramic Coated',
    hardness: 'HRC 60-65',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
    createdBy: 'admin'
  },
  {
    id: 'prod-4',
    partCode: 'IDL-150-SS304-004',
    customerName: 'Modern Packaging Systems',
    modelName: 'Web Handling System',
    rollerType: RollerType.IDLER,
    diameter: 150,
    length: 800,
    materialGrade: 'SS304',
    drawingNo: 'DRG-IDL-150-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Satin Finish',
    hardness: 'HRC 40-45',
    processTemplateId: 'template-3',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
    createdBy: 'admin'
  },
  {
    id: 'prod-5',
    partCode: 'MAG-280-EN8-005',
    customerName: 'Global Print Tech India',
    modelName: 'Rotogravure Press',
    rollerType: RollerType.MAGNETIC,
    diameter: 280,
    length: 1400,
    materialGrade: 'EN8',
    drawingNo: 'DRG-MAG-280-v1',
    revisionNo: 'R1',
    numberOfTeeth: null,
    surfaceFinish: 'Mirror Polish',
    hardness: 'HRC 58-62',
    processTemplateId: 'template-1',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
    createdBy: 'admin'
  }
]
